"""add trade_no

Revision ID: 8569dcb28843
Revises: 7bd2c4782608
Create Date: 2020-06-04 16:16:39.433787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8569dcb28843'
down_revision = '7bd2c4782608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ih_order', sa.Column('trade_no', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ih_order', 'trade_no')
    # ### end Alembic commands ###
